###  Assignment No 4 ###

"""Assignment Title : Implement Bi-gram, Tri-gram word sequence and its count in text input
data using NLTK library"""


from nltk import ngrams
from nltk.util import ngrams

#unigram model
n = 1
sentence = '"Time is a precious asset," "Everyone should value their time and others time," "Procrastinating can cause a lot of time wastage," "Time is unstoppable," "Once gone, it cannot come back," "A person needs to value time to touch great heights," "Aligning work as per time is an important skill to succeed in life," "Every minute and every second should be utilized to the best," "Time is very precious for kids too, in their early ages," "It helps them in being disciplined to achieve whatever they want" '

unigrams = ngrams(sentence.split(), n)
print(f"\n***********   UNIGRAM    ************************")
for item in unigrams:
    print(item)
#bigram model
n = 2
sentence = '"Time is a precious asset," "Everyone should value their time and others time," "Procrastinating can cause a lot of time wastage," "Time is unstoppable," "Once gone, it cannot come back," "A person needs to value time to touch great heights," "Aligning work as per time is an important skill to succeed in life," "Every minute and every second should be utilized to the best," "Time is very precious for kids too, in their early ages," "It helps them in being disciplined to achieve whatever they want" '

unigrams = ngrams(sentence.split(), n)
print(f"\n***********   BIGRAM    ************************")
for item in unigrams:
    print(item)

#trigram model
n = 3
sentence = '"Time is a precious asset," "Everyone should value their time and others time," "Procrastinating can cause a lot of time wastage," "Time is unstoppable," "Once gone, it cannot come back," "A person needs to value time to touch great heights," "Aligning work as per time is an important skill to succeed in life," "Every minute and every second should be utilized to the best," "Time is very precious for kids too, in their early ages," "It helps them in being disciplined to achieve whatever they want" '
unigrams = ngrams(sentence.split(), n)
print(f"\n***********   TRIGRAM    ************************")
for item in unigrams:
    print(item)


'''
***********   UNIGRAM    ************************
('"Time',)
('is',)
('a',)
('precious',)
('asset,"',)
('"Everyone',)
('should',)
('value',)
('their',)
('time',)
('and',)
('others',)
('time,"',)
('"Procrastinating',)
('can',)
('cause',)
('a',)
('lot',)
('of',)
('time',)
('wastage,"',)
('"Time',)
('is',)
('unstoppable,"',)
('"Once',)
('gone,',)
('it',)
('cannot',)
('come',)
('back,"',)
('"A',)
('person',)
('needs',)
('to',)
('value',)
('time',)
('to',)
('touch',)
('great',)
('heights,"',)
('"Aligning',)
('work',)
('as',)
('per',)
('time',)
('is',)
('an',)
('important',)
('skill',)
('to',)
('succeed',)
('in',)
('life,"',)
('"Every',)
('minute',)
('and',)
('every',)
('second',)
('should',)
('be',)
('utilized',)
('to',)
('the',)
('best,"',)
('"Time',)
('is',)
('very',)
('precious',)
('for',)
('kids',)
('too,',)
('in',)
('their',)
('early',)
('ages,"',)
('"It',)
('helps',)
('them',)
('in',)
('being',)
('disciplined',)
('to',)
('achieve',)
('whatever',)
('they',)
('want"',)

***********   BIGRAM    ************************
('"Time', 'is')
('is', 'a')
('a', 'precious')
('precious', 'asset,"')
('asset,"', '"Everyone')
('"Everyone', 'should')
('should', 'value')
('value', 'their')
('their', 'time')
('time', 'and')
('and', 'others')
('others', 'time,"')
('time,"', '"Procrastinating')
('"Procrastinating', 'can')
('can', 'cause')
('cause', 'a')
('a', 'lot')
('lot', 'of')
('of', 'time')
('time', 'wastage,"')
('wastage,"', '"Time')
('"Time', 'is')
('is', 'unstoppable,"')
('unstoppable,"', '"Once')
('"Once', 'gone,')
('gone,', 'it')
('it', 'cannot')
('cannot', 'come')
('come', 'back,"')
('back,"', '"A')
('"A', 'person')
('person', 'needs')
('needs', 'to')
('to', 'value')
('value', 'time')
('time', 'to')
('to', 'touch')
('touch', 'great')
('great', 'heights,"')
('heights,"', '"Aligning')
('"Aligning', 'work')
('work', 'as')
('as', 'per')
('per', 'time')
('time', 'is')
('is', 'an')
('an', 'important')
('important', 'skill')
('skill', 'to')
('to', 'succeed')
('succeed', 'in')
('in', 'life,"')
('life,"', '"Every')
('"Every', 'minute')
('minute', 'and')
('and', 'every')
('every', 'second')
('second', 'should')
('should', 'be')
('be', 'utilized')
('utilized', 'to')
('to', 'the')
('the', 'best,"')
('best,"', '"Time')
('"Time', 'is')
('is', 'very')
('very', 'precious')
('precious', 'for')
('for', 'kids')
('kids', 'too,')
('too,', 'in')
('in', 'their')
('their', 'early')
('early', 'ages,"')
('ages,"', '"It')
('"It', 'helps')
('helps', 'them')
('them', 'in')
('in', 'being')
('being', 'disciplined')
('disciplined', 'to')
('to', 'achieve')
('achieve', 'whatever')
('whatever', 'they')
('they', 'want"')

***********   TRIGRAM    ************************
('"Time', 'is', 'a')
('is', 'a', 'precious')
('a', 'precious', 'asset,"')
('precious', 'asset,"', '"Everyone')
('asset,"', '"Everyone', 'should')
('"Everyone', 'should', 'value')
('should', 'value', 'their')
('value', 'their', 'time')
('their', 'time', 'and')
('time', 'and', 'others')
('and', 'others', 'time,"')
('others', 'time,"', '"Procrastinating')
('time,"', '"Procrastinating', 'can')
('"Procrastinating', 'can', 'cause')
('can', 'cause', 'a')
('cause', 'a', 'lot')
('a', 'lot', 'of')
('lot', 'of', 'time')
('of', 'time', 'wastage,"')
('time', 'wastage,"', '"Time')
('wastage,"', '"Time', 'is')
('"Time', 'is', 'unstoppable,"')
('is', 'unstoppable,"', '"Once')
('unstoppable,"', '"Once', 'gone,')
('"Once', 'gone,', 'it')
('gone,', 'it', 'cannot')
('it', 'cannot', 'come')
('cannot', 'come', 'back,"')
('come', 'back,"', '"A')
('back,"', '"A', 'person')
('"A', 'person', 'needs')
('person', 'needs', 'to')
('needs', 'to', 'value')
('to', 'value', 'time')
('value', 'time', 'to')
('time', 'to', 'touch')
('to', 'touch', 'great')
('touch', 'great', 'heights,"')
('great', 'heights,"', '"Aligning')
('heights,"', '"Aligning', 'work')
('"Aligning', 'work', 'as')
('work', 'as', 'per')
('as', 'per', 'time')
('per', 'time', 'is')
('time', 'is', 'an')
('is', 'an', 'important')
('an', 'important', 'skill')
('important', 'skill', 'to')
('skill', 'to', 'succeed')
('to', 'succeed', 'in')
('succeed', 'in', 'life,"')
('in', 'life,"', '"Every')
('life,"', '"Every', 'minute')
('"Every', 'minute', 'and')
('minute', 'and', 'every')
('and', 'every', 'second')
('every', 'second', 'should')
('second', 'should', 'be')
('should', 'be', 'utilized')
('be', 'utilized', 'to')
('utilized', 'to', 'the')
('to', 'the', 'best,"')
('the', 'best,"', '"Time')
('best,"', '"Time', 'is')
('"Time', 'is', 'very')
('is', 'very', 'precious')
('very', 'precious', 'for')
('precious', 'for', 'kids')
('for', 'kids', 'too,')
('kids', 'too,', 'in')
('too,', 'in', 'their')
('in', 'their', 'early')
('their', 'early', 'ages,"')
('early', 'ages,"', '"It')
('ages,"', '"It', 'helps')
('"It', 'helps', 'them')
('helps', 'them', 'in')
('them', 'in', 'being')
('in', 'being', 'disciplined')
('being', 'disciplined', 'to')
('disciplined', 'to', 'achieve')
('to', 'achieve', 'whatever')
('achieve', 'whatever', 'they')
('whatever', 'they', 'want"')
'''
